#!/usr/bin/env tsx
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { parseRoadmap, type RoadmapItem, roadmapNameFromFile } from "./check-roadmap.js";

export type NodeStatus = "open" | "blocked" | "done";

export interface GraphNode {
	id: string;
	title: string;
	status: NodeStatus;
	roadmap: string;
}

export interface GraphEdge {
	from: string;
	to: string;
}

export interface Graph {
	nodes: GraphNode[];
	edges: GraphEdge[];
}

export interface UnknownDepError {
	item: string;
	unknown: string;
	roadmap: string;
}

const TOOL_ID_RE = /^TOOL-\d+$/;

export function parseDeps(raw: string): { ids: string[]; blockedExternal: boolean } {
	const trimmed = raw.trim();
	if (trimmed === "" || trimmed === "—" || trimmed === "-") {
		return { ids: [], blockedExternal: false };
	}
	if (/^blocked:/i.test(trimmed)) {
		return { ids: [], blockedExternal: true };
	}
	const ids = trimmed
		.split(",")
		.map((t) => t.trim())
		.filter((t) => TOOL_ID_RE.test(t));
	return { ids, blockedExternal: false };
}

function numericSuffix(id: string): number {
	const m = /-(\d+)$/.exec(id);
	return m ? Number.parseInt(m[1], 10) : 0;
}

export function buildGraph(items: RoadmapItem[]): { graph: Graph; unknown: UnknownDepError[] } {
	const known = new Map<string, RoadmapItem>();
	for (const item of items) {
		if (!known.has(item.id)) known.set(item.id, item);
	}

	const nodes: GraphNode[] = [];
	const edges: GraphEdge[] = [];
	const unknown: UnknownDepError[] = [];
	const seenNode = new Set<string>();

	for (const item of items) {
		if (seenNode.has(item.id)) continue;
		seenNode.add(item.id);

		const { ids: depIds, blockedExternal } = parseDeps(item.deps);
		let status: NodeStatus;
		if (item.status === "done") {
			status = "done";
		} else if (blockedExternal) {
			status = "blocked";
		} else {
			let blocked = false;
			for (const dep of depIds) {
				const depItem = known.get(dep);
				if (depItem && depItem.status !== "done") {
					blocked = true;
					break;
				}
			}
			status = blocked ? "blocked" : "open";
		}

		nodes.push({ id: item.id, title: item.title, status, roadmap: item.roadmap });

		for (const dep of depIds) {
			if (known.has(dep)) {
				edges.push({ from: dep, to: item.id });
			} else {
				unknown.push({ item: item.id, unknown: dep, roadmap: item.roadmap });
			}
		}
	}

	nodes.sort((a, b) => numericSuffix(a.id) - numericSuffix(b.id) || a.id.localeCompare(b.id));
	edges.sort((a, b) => a.from.localeCompare(b.from) || a.to.localeCompare(b.to));

	return { graph: { nodes, edges }, unknown };
}

function escapeTitle(title: string): string {
	return title.replace(/\n/g, " ").replace(/"/g, "&quot;").replace(/\[/g, "&#91;").replace(/\]/g, "&#93;");
}

export function emitMermaid(graph: Graph): string {
	const lines: string[] = ["flowchart LR", "  classDef done stroke-dasharray: 5 5,opacity:0.6", ""];

	for (const node of graph.nodes) {
		const title = escapeTitle(`${node.id}. ${node.title}`);
		if (node.status === "done") {
			lines.push(`  ${node.id}["${title}"]:::done`);
		} else if (node.status === "blocked") {
			lines.push(`  ${node.id}("${title}")`);
		} else {
			lines.push(`  ${node.id}["${title}"]`);
		}
	}

	if (graph.edges.length > 0) {
		lines.push("");
		for (const edge of graph.edges) {
			lines.push(`  ${edge.from} --> ${edge.to}`);
		}
	}

	return lines.join("\n") + "\n";
}

function findRepoRoot(): string {
	const here = dirname(fileURLToPath(import.meta.url));
	return resolve(here, "..");
}

function loadAllItems(docsDir: string): RoadmapItem[] {
	const files = readdirSync(docsDir)
		.filter((f) => /^roadmap-.+\.md$/.test(f))
		.sort();
	const items: RoadmapItem[] = [];
	for (const f of files) {
		const body = readFileSync(join(docsDir, f), "utf8");
		items.push(...parseRoadmap(body, roadmapNameFromFile(f)));
	}
	return items;
}

const USAGE = "Usage: tsx scripts/roadmap-graph.ts [--stdout]";

export function runCli(argv: string[], repoRoot: string = findRepoRoot()): number {
	let toStdout = false;
	for (const arg of argv) {
		if (arg === "--stdout") {
			toStdout = true;
		} else {
			process.stderr.write(`unknown flag: ${arg}\n${USAGE}\n`);
			return 1;
		}
	}

	const docsDir = join(repoRoot, "docs");
	const items = loadAllItems(docsDir);
	const { graph, unknown } = buildGraph(items);

	if (unknown.length > 0) {
		for (const err of unknown) {
			process.stderr.write(`${err.item} [${err.roadmap}] references unknown dep ${err.unknown}\n`);
		}
		return 1;
	}

	const body = emitMermaid(graph);

	if (toStdout) {
		process.stdout.write(body);
		return 0;
	}

	const outPath = join(docsDir, "dep-graph.md");
	const wrapped = `# Roadmap Dependency Graph\n\n<!-- Generated by \`pnpm graph:roadmap\` — do not edit. -->\n\n\`\`\`mermaid\n${body}\`\`\`\n`;
	writeFileSync(outPath, wrapped);
	return 0;
}

const isMain = import.meta.url === pathToFileURL(process.argv[1] ?? "").href;
if (isMain) {
	process.exit(runCli(process.argv.slice(2)));
}
